# Generated by Django 4.2.20 on 2025-05-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campreg', '0002_individual_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='registered_families',
        ),
        migrations.AddField(
            model_name='camp',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
