# Generated by Django 4.2.20 on 2025-05-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campreg', '0003_remove_camp_registered_families_camp_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='registered_families',
            field=models.ManyToManyField(blank=True, to='campreg.family'),
        ),
    ]
