# Generated by Django 4.2.20 on 2025-05-09 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campreg', '0004_camp_registered_families'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='campreg.camp')),
            ],
        ),
    ]
